### ISSUE TITLE
Milestone 1: Basic Functioning Chatroom

### ISSUE THREAD

**Issue by laosb** [Blah-IM/rfcs#2]
## Protocol & Backend
- [ ] #1 
- [ ] JWKs-based User Profile Definition ([previous attempt](https://doc-swift-types.moise.im/documentation/moisetypes/moiseidentity))
- [ ] Message definition ([previous attempt](https://doc-swift-types.moise.im/documentation/moisetypes/moisemessage))
  - We only consider basic text & formatting in this milestone: No stickers, reactions, media & files, etc.
- [ ] Chat Server API ()
  - [ ] Message Ingest Endpoint
  - [ ] Message History Endpoint ([Better if we go JSONFeed compatible](https://t.me/c/1959311043/560))

## UI & UX
- [x] Chat List
- [x] Chat

**Comment by laosb** [comment]
@laosb 歡迎大家grab a part來寫rfc或者code prototype
